version: '2'

services:
  php:
    build: ./php
    volumes:
      - ./../database:/var/database
    depends_on:
      - mysql_database
    tty: true

  mysql_database:
    build: ./mysql_database
    command: mysqld --sql_mode=""

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - '80:8080'
